In [1]:
#numpy 

import numpy as np


print (np. identity(3))   #to print identity matrix but values are float

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [2]:
#to make value as int

In [3]:
y = np.identity(3)
print (y)
print(y.dtype)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
float64


In [4]:
x = y.astype(int)  # astype is used to convert the values
print(x)
print (x.dtype)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
int32


In [5]:
#to create a random matrix with random values from low to high

In [6]:
print (np.random.randint(5,11,size=(3,3)))

[[ 9 10  6]
 [ 9 10  8]
 [ 5  7  9]]


In [7]:
#numpy.arange

In [8]:
print(np.arange(10))  #n-1 values will be printed

[0 1 2 3 4 5 6 7 8 9]


In [9]:
print(np.arange(1,11))  # this is used to include 1 and remove 11

[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
print (np.arange(1,21,3))  # so 3 is gap 1 is included and 21 is excluded 

[ 1  4  7 10 13 16 19]


In [11]:
print (np.arange(1,10, dtype=np.float)) # DEFAULT DATA TYPE OF INTEGER IS CHANGED TO FLOAT

[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [12]:
#numpy.linspace    returns number spaces 


In [13]:
print(np.linspace(1,50,num=3))  #so interval is created at total values of 3

[  1.   25.5  50. ]


In [14]:
#numpu.indices   #tells the indedxes

In [15]:
print(np.indices((3,4)))

[[[0 0 0 0]
  [1 1 1 1]
  [2 2 2 2]]

 [[0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]]]


In [16]:
# Datatypes in numpy 

In [17]:
x = np.array ([1,2,3,4,5])
y = np.array([1.,2.,3.,4.,5.])
type(x)
print (type(x))
print("data type of x array is", x.dtype)
print("data type of y array is", y.dtype)

<class 'numpy.ndarray'>
data type of x array is int32
data type of y array is float64


In [18]:
z = np.array([1,2,3,4,5], dtype=np.float)# forcefully changinhg the value to float and for float 32 do it float32
print(z)

[ 1.  2.  3.  4.  5.]


In [19]:
#numpy. reshape

In [20]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [21]:
a.shape # means there are 6 elemnts in 1d array 

(6,)

In [22]:
#reshape function 

In [23]:
a.reshape((3,2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [24]:
a.reshape((2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
a.reshape((6,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [26]:
twod = np.array([[1,2,3],[4,5,6]])
print (twod)

[[1 2 3]
 [4 5 6]]


In [27]:
twod.shape

(2, 3)

In [28]:
twod.reshape((6))

array([1, 2, 3, 4, 5, 6])

In [29]:
twod.reshape((6,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [30]:
print(np.arange(4).reshape(2,2))

[[0 1]
 [2 3]]


In [31]:
a = np.arange(4).reshape(2,2)
print (a)

[[0 1]
 [2 3]]


In [32]:
np.transpose(a) # makes the transpose of the array

array([[0, 2],
       [1, 3]])

In [33]:
#converting list into an array 

In [34]:
list = [10,20,30,40]
print (list)

[10, 20, 30, 40]


In [35]:
listarray = np.array(list)
print(listarray)

[10 20 30 40]


In [36]:
#slicing

In [37]:
a = np.array([1,2,3,4,5,6,7,8])
print(a)
print (a[:5])
print (a[0:5])
print(a[0:6:2]) #remove every 2 elements

[1 2 3 4 5 6 7 8]
[1 2 3 4 5]
[1 2 3 4 5]
[1 3 5]


In [38]:
a = np.arange(51)
print(a[0::2])

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


In [39]:

import pandas as pd


In [40]:
# series

In [41]:
data = np.array([1,2,3,4,5,6])
print(data)

[1 2 3 4 5 6]


In [42]:
s = pd.Series(data)
print(s)                   # thisgives us the labelled array

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int32


In [43]:
data = np.array(['a','b','c','d','e','f'])
s = pd.Series(data)
print(s)


0    a
1    b
2    c
3    d
4    e
5    f
dtype: object


In [44]:
s = pd.Series(data,index=[100,200,300,400,500,600])
print(s)

100    a
200    b
300    c
400    d
500    e
600    f
dtype: object


In [45]:
#dataframe

In [46]:
mydata = {'gender':['M','F','M'], 'emp_id':[1,2,3], 'age' :[27,22,21]}

In [47]:
df = pd.DataFrame(mydata, columns = ['emp_id', 'age', 'gender'])
print(df)

   emp_id  age gender
0       1   27      M
1       2   22      F
2       3   21      M


In [48]:
#Read a csv file 
df = pd.read_csv("D:\\hackveda\\data.csv")
print(df)

     Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  \
0             1           5.1          3.5           1.4          0.2   
1             2           4.9          3.0           1.4          0.2   
2             3           4.7          3.2           1.3          0.2   
3             4           4.6          3.1           1.5          0.2   
4             5           5.0          3.6           1.4          0.2   
5             6           5.4          3.9           1.7          0.4   
6             7           4.6          3.4           1.4          0.3   
7             8           5.0          3.4           1.5          0.2   
8             9           4.4          2.9           1.4          0.2   
9            10           4.9          3.1           1.5          0.1   
10           11           5.4          3.7           1.5          0.2   
11           12           4.8          3.4           1.6          0.2   
12           13           4.8          3.0         

In [49]:
#csv format --> Text Format 
df1 = pd.read_csv("D:\\hackveda\\iris.txt", sep = "\t")
print(df1)

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
9             4.9          3.1           1.5          0.1     setosa
10            5.4          3.7           1.5          0.2     setosa
11            4.8          3.4           1.6          0.2     setosa
12            4.8          3.0           1.4          0.1     setosa
13            4.3          3.0    

In [50]:
df2 = pd.read_excel("D:\\hackveda\\mtcars.xlsx") #address of excel file
print(df2)

                  model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.

In [51]:
df2 = pd.read_excel("D:\\hackveda\\mtcars.xlsx", "Sheet2", encoding = 'utf-8')
print(df2)


   Id   Name
0    1  John
1    2  John
2    3  John
3    4  John
4    5  John
5    6  John
6    7  John
7    8  John


In [52]:
# Read a file from URL

import urllib
myurl = "http://devanshushukla.com/hackveda.in/pythonfiles/stock.csv" # saving the Url in an object
urlrequest = urllib.request.Request(myurl)   # sending a request
file = urllib.request.urlopen(urlrequest)    # Request to open a file
df3 = pd.read_csv(file)  #read the csv
print(df3)  

     company            eps  revenue price      people
0     Google          27.82       87   845      Sundar
1  Microsoft           4.61      484    65  Bill Gates
2      Apple             -1       85    64       Steve
3        HCL  not available       50  1023        n.a.
4      Wipro            5.6       -1  n.a.  Ravi Raman


In [53]:



df4 = pd.read_csv("D:\\hackveda\\mtcars.csv")
print(df4)

                  model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.

In [54]:
#top 5 rows
df4.head(5)

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [55]:
df4.tail(5)

model   mpg  cyl   disp   hp  drat     wt  qsec  vs  am  gear  \
27    Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.9   1   1     5   
28  Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.5   0   1     5   
29    Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.5   0   1     5   
30   Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.6   0   1     5   
31      Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.6   1   1     4   

    carb  
27     2  
28     4  
29     6  
30     8  
31     2

In [56]:
df4.columns

Index(['model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am',
       'gear', 'carb'],
      dtype='object')

In [57]:
df4.dtypes

model     object
mpg      float64
cyl        int64
disp     float64
hp         int64
drat     float64
wt       float64
qsec     float64
vs         int64
am         int64
gear       int64
carb       int64
dtype: object

In [58]:
df4['model'].unique

<bound method Series.unique of 0               Mazda RX4
1           Mazda RX4 Wag
2              Datsun 710
3          Hornet 4 Drive
4       Hornet Sportabout
5                 Valiant
6              Duster 360
7               Merc 240D
8                Merc 230
9                Merc 280
10              Merc 280C
11             Merc 450SE
12             Merc 450SL
13            Merc 450SLC
14     Cadillac Fleetwood
15    Lincoln Continental
16      Chrysler Imperial
17               Fiat 128
18            Honda Civic
19         Toyota Corolla
20          Toyota Corona
21       Dodge Challenger
22            AMC Javelin
23             Camaro Z28
24       Pontiac Firebird
25              Fiat X1-9
26          Porsche 914-2
27           Lotus Europa
28         Ford Pantera L
29           Ferrari Dino
30          Maserati Bora
31             Volvo 142E
Name: model, dtype: object>

In [59]:
df4[['hp','vs']]

hp  vs
0   110   0
1   110   0
2    93   1
3   110   1
4   175   0
5   105   1
6   245   0
7    62   1
8    95   1
9   123   1
10  123   1
11  180   0
12  180   0
13  180   0
14  205   0
15  215   0
16  230   0
17   66   1
18   52   1
19   65   1
20   97   1
21  150   0
22  150   0
23  245   0
24  175   0
25   66   1
26   91   0
27  113   1
28  264   0
29  175   0
30  335   0
31  109   1